format = """
$character\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
[❯ ](purple)\
"""

add_newline = false

[directory]
style = "bold blue"

[character]
success_symbol = "[ π](bold fg:green)"
error_symbol = "[ π](bold fg:red)"
vimcmd_symbol = "[ ❮](green)"

[git_branch]
format = "[$branch ]($style)"
style = "bold green"

[git_status]
format = "[[(✗ $conflicted$untracked$modified$staged$renamed$deleted)]($style)($ahead_behind$stashed )]($style)"
style = "bold yellow"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-black"

[cmd_duration]
format = "[$duration ]($style)"
style = "yellow"
