#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color '#5d4d7a'
bspc config normal_border_color '#444155'

bspc rule -a Spotify desktop='^10' state=tiled
bspc rule -a Emacs desktop='^1' state=tiled
#bspc rule -a Firefox desktop='^2'

killall polybar
polybar

# Notifications
/usr/bin/dunst &
